### PR TITLE
Switch to volumetric measurements instead of lake depth

### PR DESCRIPTION
**Pull request by treyp**
Hey guys,

Everyone uses the lake depth as a measurement of whether or not it's full, but that's hardly a measure of fullness at all. Because the lake doesn't have flat sides like a cylinder or cube, but is closer to a cone shape, the depth of the lake misleads people into believing we're almost there when we aren't.

In this pull request, I kept the same LCRA data source, but switch to displaying volumes instead. In doing so, I also switch the left notches to either quarters or tenths, keeping your definition of a screen that's tall enough to display more notches (min-height: 600px). I wrote the CSS in the appropriate SCSS file and then compiled it in the correct CSS file using Sass.

I also removed the Sass cache files and git-ignored them so they don't update on every style commit.

Hope you guys agree with this, and if it needs any syntactic clean up or other work, just let me know!

Thanks!

### CODE REVIEW

**Comment by sophshep** [comment]
Hi Trey,

Thanks for submitting this!! You are right and you're not the first person to call us out on having a less-than-accurate representation of the lake. However, we like the drama and simplicity of showing the height visually. Rather than replace that data, would you be able to add on the volume as a secondary metric? Some ideas we've talked about are: 1. have a switcher in the top right that switches between lake height and volume 2. underneath "20 ft to go" say "lake is at X% capacity 3. Create a secondary page that shows volume instead of height.

Sophie

**Comment by treyp** [comment]
Hey Sophie. Thanks for the feedback.

I went ahead and implemented both ways with a switch at the top right using depth as the default.

I put the current display in the location hash, and I use that on page load to determine which display to start out with. So, if people like me bookmark the volume one, it should load that choice each time without requiring any clicking. Same for link sharing.

I also put a 5 minute poll in there to update the data. I can't tell how frequently LCRA refreshes the data. It may be 30 minutes. If that's the case, we can update the number. 5 minutes seems like an okay choice for now.

Lastly, the notches were slightly off. I fixed that. The bottom of the notch is now the exact number you'd expect. I'd like to center the notch perfectly, bringing it down 1.5 pixels, but it wasn't worth the time right now.

You can preview this all on my fork's GH page: http://treyp.github.io/isthelakefullyet/. Let me know if you've got any more feedback. :smiley:

**Comment by sophshep** [comment]
This rules!!! Thank you so much! Merging now.

Re: data updating, @ryanirelan is working on something that refreshes & saves the data every 15 minutes (how often the LRCA site gets updated). This way we have past data in case we want to build anything with it later on.

**Comment by Brilliantcrank** [comment]
Nice work Trey! #socool

**Pull request merged**
