### PR TITLE
Fix so depth notches don't start at sea level (#22)

### LINKED ISSUE #22: lake is measured in ft about sea level so empty is not 0 ft.
hi, nice app!  I'm being nit picky here...  The feet graph shouldn't start a 0, because that's 0 feet above sea level.  The historic low of Lake Travis is around 614 feet above sea level.  I think the bottom is actually 600 feet or so.  If you make the feet graph start a the bottom above sea level the the feet graph and volume graph will be on much closer scales.

### PR DESCRIPTION
**Pull request by treyp**
Fixes #22

One of the problems I encountered with this is the empty notch. I didn't want to put empty at the very bottom of the page or else the label would look funky. So, for now, there's water below the empty mark.
image

I made [a branch that adds a sand bar under the empty mark](https://github.com/treyp/isthelakefullyet/tree/sand-bar), but it doesn't look good with the donate text there. I kept it on a separate branch until I can think of a better solution.
image

### CODE REVIEW

**Comment by teleject** [comment]
Do we know that 471ft is the bed level? If so, where is that information sourced? I'd like to double-check this information before we add it.

**Comment by treyp** [comment]
That number came from Wikipedia. It's the full level minus the max depth. http://www.wikiwand.com/en/Lake_Travis

**Comment by teleject** [comment]
Is there a source listed at Wikipedia for the depth? I didn't see one associated with max depth, but will admit I didn't check all of them out yet. If/when we put in the values and visuals for depth, I want to be very sure so as not to a) confuse people and b) give them the outdated info.

**Comment by lvaughn** [comment]
Randomly came across this repo, and happened to have seen the answer to this recently.

According to the latest hydro survey (2008: http://www.twdb.texas.gov/hydro_survey/travis/2008-07/Travis2008_FinalReport.pdf), it looks like they consider the lake as having reservoir capacity at 501 feet (and change).  The table at the start of appendix A starts at 501 feet.  Note that this is likely higher than it used to be, as this survey take sediment settling to the bottom of the lake over the years in to account.  

Note: I didn't read the whole report, so perhaps the lake is deeper in parts, but they don't count that water as usable.

**Comment by treyp** [comment]
That's a lot of research there, but seems pretty legit. I've updated it to use the 501.0 number they mention. I think we should just put this out there and update based on any new info. Or just switch to volume entirely :)

**Comment by treyp** [comment]
we're getting so close to full!

just wanted to bump this and the other pull requests. haven't seen a response in a while.

**Pull request merged**
